### ISSUE TITLE
SNES vertical tearing

### ISSUE THREAD

**Issue by customcarvin** [Sakitoshi/retropie-crt-tvout#13]
Hi, 

I'm big fan of the project! Thanks for your work! Most of the systems that you have supported seem to function properly for me without any big noticeable issues, except for the SNES shader, where I experience tearing while playing. A couple good examples to use are, Donkey Kong Country 2: In the first level when the ship is bobbing up and down I notice the tearing easily, and, Super Mario RPG: During the intro as the screen pans down towards Peach, tearing is very noticeable. 

I have a couple questions in addition to the issue above... this is probably not the proper place to start discussion (I'm guessing this section should be used for bug tracking only) but I have no other means of communication (I found no email in the readme)...

First question: Is there anyway to adjust the position and/or scale of the output (without messing with pi overscan config params)? I tried altering the X and Y values within the Retroarch menu while in game, but it didn't do anything; my CRT is a dirt-cheap "Apex" and has no options for centering or scaling so most of the corner graphics are always cut off. I never know how many lives I have in Sonic games, that's how bad it is.

Second question: I have also tried this project: https://github.com/ektgit/snap-shader-240p
Is there anyway that you could tell me what the differences are between your implementation and theirs (besides the fact that the snap-shader is a one-size-fits-all solution, of course)? I'm trying to obtain the most optimized, lowest input lag experience possible with the pi.

Thanks again for your work, and your time!

Regards,

**Comment by Nibby99** [comment]
Please let me know if you get anywhere with this. I am loving my Retropie finally on a CRT (little 14" Toshiba with s-video / component also).  The one thing I notice is some sort of scaling issues in SNES that double up some pixels (IE: in SuperMetroid I can notice when viewing map the grid is all whacky looking and diagonal lines every so often have doubled up pixels). I can nearly live with it but I'd love for it to be better. How did you find that snap-shader? from how I read that though the images aren't stretched to fill the screen.

**Comment by customcarvin** [comment]
Hi Nibby99,

I agree, playing on a CRT is very satisfying. I'm going to check out Super Metroid to see if I can replicate what you're describing. I'm not sure how I found that snap shader, I was just Google'ing around one day with keywords, "CRT", "240p", and "pi", and it just happened to pop up, I think?

Hopefully we get this all sorted; SNES was my favorite retro console, by far. That snap shader seems to work pretty well, though I'm only using it for SNES and just for the time being (I'm hoping that this one gets fixed), as the snap shader *seems* to introduce a bit more input lag... it could just be a placebo effect, but I feel like there is just a hair more delay when playing games like Mario World than with this shader. In addition, there seems to also be a bit of stutter, on occasion, with the snap shader. Though, admittedly, I'm kind of a novice when it comes to some of this stuff, so it might be something I'm doing incorrectly...

Anyway, I'll try and keep you posted. Could you do the same?

Regards,

**Comment by Nibby99** [comment]
Absolutely. I am working with someone else on this issue too and will be sending him screenshots. I'll post before and after photos if I can fix the scaling issue and what I did to do such.

**Comment by Sakitoshi** [comment]
@customcarvin the shader has nothing to do with the tearing and if one system would exhibit tearing all would as the tv-out shader is basically the same for all just with slightly tweaked settings.
my guess would be the emulator you are using, I'm using snes9x 2010 and I haven't updated since some time now.

the shader preset applied to sega genesis/megadrive (and for extension sega cd and 32x) has no centering shader, so you can move and shrink/stretch the image around as much as you please with the retroarch menu, but some other consoles do use a vertical centering shader (ps1, ms-dos, atari 7800 and arcade) and those you can move around in any axis but only shrink/stretch horizontally because the shader is there to take care of the multiple vertical resolutions those systems use.
now other systems use a more strict centering shader (neogeo, pc engine/pce-cd and all the portables when using border or pixelperfect modes) that only allows moving the image around, it is like that because it was easier for me to do it that way I guess, I can't remember why.

as for the difference, my project aims to mimic as close as possible the output of the real (ntsc) consoles taking into account the limitations that the composite out of the raspberry pi has. I have done everything through observation and some investigation to get the right numbers.
the arcade and portable systems are a bonus because I can, that's why I don't intend to add proper support for vertical arcade games.

@Nibby99 that duplication can be ghosting, for what I know it happens a lot on old crt's because of old age or descalibration. I don't know if it can be fixed or anything, my tv also exhibit that problem, it has nothing to do with the configurations. it doesn't appear when you connect the raspi to an hdtv.

I took some pictures of how things look on my 14'' samsung ct3312v2 from 1989
![dsc_0210](https://user-images.githubusercontent.com/39132563/47766426-59de6480-dcad-11e8-810d-cd097316725c.JPG)
![dsc_0216](https://user-images.githubusercontent.com/39132563/47766429-5d71eb80-dcad-11e8-8f1f-bd0e11933ab3.JPG)

**Comment by chipsnblip** [comment]
it appears the problem some users are experiencing lies with recent changes to retroarch index values. so those running an updated retropie setup will likely need to change all instances of `aspect_ratio_index = "22"` to `aspect_ratio_index = "23"`.

i'm running a somewhat outdated build, and can't confirm this.

**Comment by Sakitoshi** [comment]
welp, leave it to them to break things. that's why I'm always reluctant to update.
I looked around and they did change the aspect_ratio_index numbers in RA 1.7.4.
I guess I should update all the configs and add a warning about how it would stop working properly for older installs.

and while looking for the documentation that states the change (no, they didn't documented the change or said anything about it in the blog) I also saw that they added some features that mess with v-sync, it wouldn't be strange if those changes are what are causing tearing for you @customcarvin .

**Comment by Sakitoshi** [comment]
#15 should fix the positioning issue. I'll be testing today if the latest retroarch is also responsible of the tearing issue.

**Comment by customcarvin** [comment]
Thank you all for figuring this out!

**Comment by Nibby99** [comment]
Hopefully this fixes it for you. It did for me. Let me know how you make out. I got it working super duper in all consoles, still working on MAME configs especially vertical ones.

**Comment by customcarvin** [comment]
Tested tonight, and SNES is displaying as it should (no tearing). Thank you all again very much!
