### ISSUE TITLE
EmulationStation still cropping off bottom commands? Console command screens too?

### ISSUE THREAD

**Issue by MessiahMozgus** [Sakitoshi/retropie-crt-tvout#47]
I freshly installed retropie and your tweaks, read all instructions, uncommented the optional settings except #hdmi_ignore_hotplug=1.

I saw in a comment you posted you said you fixed ES from getting cropped by adding the autostart.sh file? Well it's still cropped here. Yes, I also followed instructions to edit out "-yres 448" on "configs/all/runcommand-onstart.sh" and "-yres 480" on "configs/all/runcommand-onend.sh". The text on those old console command screens is also still being cropped. Unable to read any text on the outer edges.

This is the last remaining issue I have and I hope you're still around to provide a tip. I'm running this over AV composite to a Sony Wega Trinitron 32inch, but even using HDMI 480p on an LCD TV, I see the same cropping.

**Comment by Sakitoshi** [comment]
over HDMI is natural that nothing changes, the scripts are designed to not do anything over HDMI and only affect NTSC output. you should be able to see everything on yout HD TV though, check if your TV settings are cutting overscan.
over on your CRT TV, maybe it has tighter margins than mine. you can modify the values of the autostart.sh file until you are happy with the results.
specifically `--screensize 640 448 --screenoffset 38 16`

but I'm not able to test this anymore since I upgraded my pi 3 with a pi 4 and got rid of it.
and with all the updates to retropie and the raspberry pi firmware has received I would not be surprised if something broke over time since I haven't maintained this repository since early 2020.
it would be better if you check out the CRTPi project, you can see them as the successor to this configs.
https://www.reddit.com/r/crtpi/comments/m1m26k/crtpi_mega_link_thread/

**Comment by MessiahMozgus** [comment]
Yeah I edited autostart.sh values already and they apparently have no effect anymore. Weird.

But thank you for the link! I'm excited to start from scratch with that project.
